# Generated by Django 2.2 on 2021-07-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='mainapp.Color', verbose_name='Цвета'),
        ),
    ]
